server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: global-mcp-client
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

logging:
  level:
    com.deepai: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

mcp:
  client:
    default-timeout: 15000  # Increased from 5000 to 15000 (15 seconds)
    retry:
      max-attempts: 3       # Increased from 2 to 3 attempts
      backoff-multiplier: 1.5  # Increased from 1.2 to 1.5
  servers:
    mongo-mcp-server-test:
      type: stdio
      command: "java"
      args:
        - "-Dspring.profiles.active=mcp"
        - "-Dspring.main.web-application-type=none"
        - "-jar"
        - 'D:\\MCP\\MCP-workspace-bootcampToProd\\spring-boot-ai-mongo-mcp-server\\target\\spring-boot-ai-mongo-mcp-server-0.0.1-SNAPSHOT.jar'
      timeout: 20000        # Increased from 8000 to 20000 (20 seconds)
      enabled: true
      environment:
        SPRING_DATA_MONGODB_URI: "mongodb://localhost:27017/mcpserver"
        MONGO_DATABASE: "mcpserver"
