server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: global-mcp-client
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  ai:
    # Google Gemini configuration (Core API) - Enabled with valid API key
    google:
      gemini:
        enabled: true  # Enabled with working API key
        api-key: ${GEMINI_API_KEY:your-gemini-api-key-here}
        chat:
          options:
            model: gemini-1.5-flash
            temperature: 0.7
            max-tokens: 2048
    # Fallback to Ollama if Gemini is not available
    ollama:
      base-url: "http://localhost:11434"
      chat:
        options:
          model: "llama3.1:8b"
          temperature: 0.7
          max-tokens: 2048
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
#  ai:
#    ollama:
#      base-url: "http://localhost:11434"
#      chat:
#        options:
#          model: "llama3.1:8b"
#          temperature: 0.7
#          max-tokens: 2048

logging:
  level:
    com.deepai: INFO
    org.springframework.web: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# AI Configuration for custom implementation
ai:
  enabled: true
  provider: gemini
  model: gemini-1.5-flash
  api-key: ${GEMINI_API_KEY:your-gemini-api-key-here}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

mcp:
  client:
    default-timeout: 5000
    retry:
      max-attempts: 2
      backoff-multiplier: 1.2
  servers:
    oracle-mcp-server:
      type: stdio
      command: "java"
      args:
        - "-jar"
        - 'G:\\Software G\\MCP\\mcp-oracledb-server\\target\\mcp-oracledb-server-1.0.0-PRODUCTION.jar'
        - "--spring.profiles.active=mcp-run"
      timeout: 20000
      enabled: true
      environment:
        ORACLE_DB_URL: "jdbc:oracle:thin:@localhost:1521:XE"
        ORACLE_DB_USER: "C##loan_schema"
        ORACLE_DB_PASSWORD: "loan_data"
        ORACLE_HOST: "localhost"
        ORACLE_PORT: "1521"
        ORACLE_SID: "XE"
        MCP_TOOLS_EXPOSURE: "all"
        ENTERPRISE_ENABLED: "true"

---
# Server profile - disable MCP servers for REST API testing
spring:
  config:
    activate:
      on-profile: server

mcp:
  servers: {}
#    filesystem-python-mcp-server:
#      type: stdio
#      command: "D:\\MCP\\MCP-workspace-bootcampToProd\\filesystem_mcp_server\\venv\\Scripts\\python.exe"
#      args:
#        - "D:\\MCP\\MCP-workspace-bootcampToProd\\filesystem_mcp_server\\src\\main.py"
#      timeout: 8000
#      enabled: true
